#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
 # namespace: dev
  labels:
    app: nodejsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsapp
      tier: frontend
      version: 1.0.0
#pod tempalte
  template:
    metadata:
      labels:
        app: nodejsapp
        tier: frontend
        version: 1.0.0
    spec: # Pod spec
      containers:
      - name: nodejs-container
        image: ooghenekaro/nodejs:v1.0.0.RELEASE
        ports:
        - containerPort: 3000


SERVICE

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  #namespace: dev
  labels:
    app: nodejsapp
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort:3000
  selector:
    app: nodejsapp
    tier: frontend
  type: LoadBalancer



